# Generated by Django 5.0.1 on 2024-03-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
        ("products", "0003_relationalproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=255, verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="order",
            name="district",
            field=models.CharField(max_length=50, verbose_name="區"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="信箱"),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=50, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=50, verbose_name="電話"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(default=0, verbose_name="總計"),
        ),
        migrations.AlterField(
            model_name="order",
            name="zipcode",
            field=models.CharField(max_length=50, verbose_name="郵遞區號"),
        ),
        migrations.CreateModel(
            name="RelationalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1, verbose_name="數量")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relational_products",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relational_products",
                        to="products.product",
                        verbose_name="商品名稱",
                    ),
                ),
            ],
        ),
    ]
