# Generated by Django 5.0.1 on 2024-04-15 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_address_alter_order_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="district",
        ),
    ]
