# Generated by Django 5.0.1 on 2024-04-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_order_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationalproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relational_products",
                to="orders.order",
                verbose_name="訂單",
            ),
        ),
    ]
