# Generated by Django 5.0.1 on 2024-04-15 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_relationalproduct_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RelationalProduct",
        ),
    ]
